services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - /path/to/data:/data
    environment:
      - MINIO_ROOT_USER=arnabchatterjee
      - MINIO_ROOT_PASSWORD=arnabchatterjee
    command: server /data --console-address ":9001"